### ISSUE TITLE
calling XmlHttpRequest.Open doesn't work because different domain

### ISSUE THREAD

**Issue by harinpatel** [gimmi/extdirecthandler#8]
My extJs application is accessed through other gateway so page is in different domain call https:\gatewayurl\application and 
when it tries to get data it send request to http:\localserverurl\application\rpc.

XmlHttpRequest.Open doesnt support this so i wanted to use JsonP as described here http://dev.sencha.com/deploy/ext-4.0.7-gpl/docs/index.html#!/api/Ext.data.proxy.JsonP. can i still use ExtDirectHandler at server side for this? or is there any change will
be needed to done to make it compatible to work with JsonP.

Please guide me i am very new to ExtJs and extdirect framework.

**Comment by gimmi** [comment]
AFAIK Ext.Direct standard doesn't consider JSONP and this makes sense to me, because JSONP parameters must be passed via querystring and then the support would be limited only to a subset of cases.

Please use the users group https://groups.google.com/group/extdirecthandler to as questions in the future
